//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Детали.
    /// </summary>
    // *** Start programmer edit section *** (Детали CustomAttributes)

    // *** End programmer edit section *** (Детали CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДеталиE", new string[] {
            "КодДетали as \'Код детали\'",
            "Наименование as \'Наименование\'",
            "Производитель as \'Производитель\'",
            "Страна as \'Страна\'"})]
    [View("ДеталиL", new string[] {
            "КодДетали as \'Код детали\'",
            "Наименование as \'Наименование\'",
            "Производитель as \'Производитель\'",
            "Страна as \'Страна\'"})]
    public class Детали : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодДетали;
        
        private string fНаименование;
        
        private string fПроизводитель;
        
        private string fСтрана;
        
        // *** Start programmer edit section *** (Детали CustomMembers)

        // *** End programmer edit section *** (Детали CustomMembers)

        
        /// <summary>
        /// КодДетали.
        /// </summary>
        // *** Start programmer edit section *** (Детали.КодДетали CustomAttributes)

        // *** End programmer edit section *** (Детали.КодДетали CustomAttributes)
        public virtual int КодДетали
        {
            get
            {
                // *** Start programmer edit section *** (Детали.КодДетали Get start)

                // *** End programmer edit section *** (Детали.КодДетали Get start)
                int result = this.fКодДетали;
                // *** Start programmer edit section *** (Детали.КодДетали Get end)

                // *** End programmer edit section *** (Детали.КодДетали Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Детали.КодДетали Set start)

                // *** End programmer edit section *** (Детали.КодДетали Set start)
                this.fКодДетали = value;
                // *** Start programmer edit section *** (Детали.КодДетали Set end)

                // *** End programmer edit section *** (Детали.КодДетали Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Детали.Наименование CustomAttributes)

        // *** End programmer edit section *** (Детали.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Детали.Наименование Get start)

                // *** End programmer edit section *** (Детали.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Детали.Наименование Get end)

                // *** End programmer edit section *** (Детали.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Детали.Наименование Set start)

                // *** End programmer edit section *** (Детали.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Детали.Наименование Set end)

                // *** End programmer edit section *** (Детали.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Производитель.
        /// </summary>
        // *** Start programmer edit section *** (Детали.Производитель CustomAttributes)

        // *** End programmer edit section *** (Детали.Производитель CustomAttributes)
        [StrLen(255)]
        public virtual string Производитель
        {
            get
            {
                // *** Start programmer edit section *** (Детали.Производитель Get start)

                // *** End programmer edit section *** (Детали.Производитель Get start)
                string result = this.fПроизводитель;
                // *** Start programmer edit section *** (Детали.Производитель Get end)

                // *** End programmer edit section *** (Детали.Производитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Детали.Производитель Set start)

                // *** End programmer edit section *** (Детали.Производитель Set start)
                this.fПроизводитель = value;
                // *** Start programmer edit section *** (Детали.Производитель Set end)

                // *** End programmer edit section *** (Детали.Производитель Set end)
            }
        }
        
        /// <summary>
        /// Страна.
        /// </summary>
        // *** Start programmer edit section *** (Детали.Страна CustomAttributes)

        // *** End programmer edit section *** (Детали.Страна CustomAttributes)
        [StrLen(255)]
        public virtual string Страна
        {
            get
            {
                // *** Start programmer edit section *** (Детали.Страна Get start)

                // *** End programmer edit section *** (Детали.Страна Get start)
                string result = this.fСтрана;
                // *** Start programmer edit section *** (Детали.Страна Get end)

                // *** End programmer edit section *** (Детали.Страна Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Детали.Страна Set start)

                // *** End programmer edit section *** (Детали.Страна Set start)
                this.fСтрана = value;
                // *** Start programmer edit section *** (Детали.Страна Set end)

                // *** End programmer edit section *** (Детали.Страна Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДеталиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДеталиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДеталиE", typeof(IIS.Snezhko_kursovaya.Детали));
                }
            }
            
            /// <summary>
            /// "ДеталиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДеталиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДеталиL", typeof(IIS.Snezhko_kursovaya.Детали));
                }
            }
        }
    }
}
