//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "ТипОплаты as \'Тип оплаты\'",
            "Комментарий as \'Комментарий\'",
            "Сумма as \'Сумма\'",
            "Бокс as \'Бокс\'",
            "Бокс.НомерБокса as \'Номер бокса\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.Фамилия as \'Фамилия\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Бокс.НомерБокса",
            "Клиенты.Фамилия",
            "Сотрудники.Фамилия"})]
    [AssociatedDetailViewAttribute("ЗаказE", "СоставЗаказа", "СоставЗаказаE", true, "", "Состав заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказE", "Бокс", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерБокса")]
    [MasterViewDefineAttribute("ЗаказE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ЗаказE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ЗаказL", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "ТипОплаты as \'Тип оплаты\'",
            "Комментарий as \'Комментарий\'",
            "Сумма as \'Сумма\'",
            "Бокс.НомерБокса as \'Номер бокса\'",
            "Клиенты.Фамилия as \'Фамилия\'",
            "Сотрудники.Фамилия as \'Фамилия\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗаказа;
        
        private System.DateTime fДата;
        
        private string fВремя;
        
        private IIS.Snezhko_kursovaya.ТипОплаты fТипОплаты;
        
        private string fКомментарий;
        
        private double fСумма;
        
        private IIS.Snezhko_kursovaya.Бокс fБокс;
        
        private IIS.Snezhko_kursovaya.Клиенты fКлиенты;
        
        private IIS.Snezhko_kursovaya.Сотрудники fСотрудники;
        
        private IIS.Snezhko_kursovaya.DetailArrayOfСоставЗаказа fСоставЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Время CustomAttributes)

        // *** End programmer edit section *** (Заказ.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Время Get start)

                // *** End programmer edit section *** (Заказ.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (Заказ.Время Get end)

                // *** End programmer edit section *** (Заказ.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Время Set start)

                // *** End programmer edit section *** (Заказ.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Заказ.Время Set end)

                // *** End programmer edit section *** (Заказ.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Дата CustomAttributes)

        // *** End programmer edit section *** (Заказ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Дата Get start)

                // *** End programmer edit section *** (Заказ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заказ.Дата Get end)

                // *** End programmer edit section *** (Заказ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Дата Set start)

                // *** End programmer edit section *** (Заказ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заказ.Дата Set end)

                // *** End programmer edit section *** (Заказ.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.КодЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.КодЗаказа CustomAttributes)
        public virtual int КодЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.КодЗаказа Get start)

                // *** End programmer edit section *** (Заказ.КодЗаказа Get start)
                int result = this.fКодЗаказа;
                // *** Start programmer edit section *** (Заказ.КодЗаказа Get end)

                // *** End programmer edit section *** (Заказ.КодЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.КодЗаказа Set start)

                // *** End programmer edit section *** (Заказ.КодЗаказа Set start)
                this.fКодЗаказа = value;
                // *** Start programmer edit section *** (Заказ.КодЗаказа Set end)

                // *** End programmer edit section *** (Заказ.КодЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Комментарий CustomAttributes)

        // *** End programmer edit section *** (Заказ.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Комментарий Get start)

                // *** End programmer edit section *** (Заказ.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (Заказ.Комментарий Get end)

                // *** End programmer edit section *** (Заказ.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Комментарий Set start)

                // *** End programmer edit section *** (Заказ.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (Заказ.Комментарий Set end)

                // *** End programmer edit section *** (Заказ.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Сумма CustomAttributes)

        // *** End programmer edit section *** (Заказ.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Сумма Get start)

                // *** End programmer edit section *** (Заказ.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Заказ.Сумма Get end)

                // *** End programmer edit section *** (Заказ.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Сумма Set start)

                // *** End programmer edit section *** (Заказ.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Заказ.Сумма Set end)

                // *** End programmer edit section *** (Заказ.Сумма Set end)
            }
        }
        
        /// <summary>
        /// ТипОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.ТипОплаты CustomAttributes)

        // *** End programmer edit section *** (Заказ.ТипОплаты CustomAttributes)
        public virtual IIS.Snezhko_kursovaya.ТипОплаты ТипОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.ТипОплаты Get start)

                // *** End programmer edit section *** (Заказ.ТипОплаты Get start)
                IIS.Snezhko_kursovaya.ТипОплаты result = this.fТипОплаты;
                // *** Start programmer edit section *** (Заказ.ТипОплаты Get end)

                // *** End programmer edit section *** (Заказ.ТипОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.ТипОплаты Set start)

                // *** End programmer edit section *** (Заказ.ТипОплаты Set start)
                this.fТипОплаты = value;
                // *** Start programmer edit section *** (Заказ.ТипОплаты Set end)

                // *** End programmer edit section *** (Заказ.ТипОплаты Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Бокс CustomAttributes)

        // *** End programmer edit section *** (Заказ.Бокс CustomAttributes)
        [PropertyStorage(new string[] {
                "Бокс"})]
        [NotNull()]
        public virtual IIS.Snezhko_kursovaya.Бокс Бокс
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Бокс Get start)

                // *** End programmer edit section *** (Заказ.Бокс Get start)
                IIS.Snezhko_kursovaya.Бокс result = this.fБокс;
                // *** Start programmer edit section *** (Заказ.Бокс Get end)

                // *** End programmer edit section *** (Заказ.Бокс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Бокс Set start)

                // *** End programmer edit section *** (Заказ.Бокс Set start)
                this.fБокс = value;
                // *** Start programmer edit section *** (Заказ.Бокс Set end)

                // *** End programmer edit section *** (Заказ.Бокс Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Клиенты CustomAttributes)

        // *** End programmer edit section *** (Заказ.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Snezhko_kursovaya.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Клиенты Get start)

                // *** End programmer edit section *** (Заказ.Клиенты Get start)
                IIS.Snezhko_kursovaya.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (Заказ.Клиенты Get end)

                // *** End programmer edit section *** (Заказ.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Клиенты Set start)

                // *** End programmer edit section *** (Заказ.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (Заказ.Клиенты Set end)

                // *** End programmer edit section *** (Заказ.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Заказ.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Snezhko_kursovaya.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Сотрудники Get start)

                // *** End programmer edit section *** (Заказ.Сотрудники Get start)
                IIS.Snezhko_kursovaya.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Заказ.Сотрудники Get end)

                // *** End programmer edit section *** (Заказ.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Сотрудники Set start)

                // *** End programmer edit section *** (Заказ.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Заказ.Сотрудники Set end)

                // *** End programmer edit section *** (Заказ.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СоставЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.СоставЗаказа CustomAttributes)
        public virtual IIS.Snezhko_kursovaya.DetailArrayOfСоставЗаказа СоставЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Get start)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Get start)
                if ((this.fСоставЗаказа == null))
                {
                    this.fСоставЗаказа = new IIS.Snezhko_kursovaya.DetailArrayOfСоставЗаказа(this);
                }
                IIS.Snezhko_kursovaya.DetailArrayOfСоставЗаказа result = this.fСоставЗаказа;
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Get end)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Set start)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Set start)
                this.fСоставЗаказа = value;
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Set end)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Snezhko_kursovaya.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Snezhko_kursovaya.Заказ));
                }
            }
        }
    }
}
