//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Клиенты CustomAttributes)

    // *** End programmer edit section *** (Клиенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентыE", new string[] {
            "КодКлиента as \'Код клиента\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "ДатаРождения as \'Дата рождения\'",
            "НомерТелефона as \'Номер телефона\'"})]
    [AssociatedDetailViewAttribute("КлиентыE", "Автомобиль", "АвтомобильE", true, "", "Автомобиль", true, new string[] {
            ""})]
    [View("КлиентыL", new string[] {
            "КодКлиента as \'Код клиента\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "ДатаРождения as \'Дата рождения\'",
            "НомерТелефона as \'Номер телефона\'"})]
    public class Клиенты : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодКлиента;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private System.DateTime fДатаРождения;
        
        private int fНомерТелефона;
        
        private IIS.Snezhko_kursovaya.DetailArrayOfАвтомобиль fАвтомобиль;
        
        // *** Start programmer edit section *** (Клиенты CustomMembers)

        // *** End programmer edit section *** (Клиенты CustomMembers)

        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ДатаРождения Get start)

                // *** End programmer edit section *** (Клиенты.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Клиенты.ДатаРождения Get end)

                // *** End programmer edit section *** (Клиенты.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ДатаРождения Set start)

                // *** End programmer edit section *** (Клиенты.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Клиенты.ДатаРождения Set end)

                // *** End programmer edit section *** (Клиенты.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Имя CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Имя Get start)

                // *** End programmer edit section *** (Клиенты.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Клиенты.Имя Get end)

                // *** End programmer edit section *** (Клиенты.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Имя Set start)

                // *** End programmer edit section *** (Клиенты.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Клиенты.Имя Set end)

                // *** End programmer edit section *** (Клиенты.Имя Set end)
            }
        }
        
        /// <summary>
        /// КодКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.КодКлиента CustomAttributes)

        // *** End programmer edit section *** (Клиенты.КодКлиента CustomAttributes)
        public virtual int КодКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.КодКлиента Get start)

                // *** End programmer edit section *** (Клиенты.КодКлиента Get start)
                int result = this.fКодКлиента;
                // *** Start programmer edit section *** (Клиенты.КодКлиента Get end)

                // *** End programmer edit section *** (Клиенты.КодКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.КодКлиента Set start)

                // *** End programmer edit section *** (Клиенты.КодКлиента Set start)
                this.fКодКлиента = value;
                // *** Start programmer edit section *** (Клиенты.КодКлиента Set end)

                // *** End programmer edit section *** (Клиенты.КодКлиента Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (Клиенты.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.НомерТелефона Get start)

                // *** End programmer edit section *** (Клиенты.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (Клиенты.НомерТелефона Get end)

                // *** End programmer edit section *** (Клиенты.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.НомерТелефона Set start)

                // *** End programmer edit section *** (Клиенты.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (Клиенты.НомерТелефона Set end)

                // *** End programmer edit section *** (Клиенты.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Отчество CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Отчество Get start)

                // *** End programmer edit section *** (Клиенты.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Клиенты.Отчество Get end)

                // *** End programmer edit section *** (Клиенты.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Отчество Set start)

                // *** End programmer edit section *** (Клиенты.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Клиенты.Отчество Set end)

                // *** End programmer edit section *** (Клиенты.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Фамилия Get start)

                // *** End programmer edit section *** (Клиенты.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Клиенты.Фамилия Get end)

                // *** End programmer edit section *** (Клиенты.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Фамилия Set start)

                // *** End programmer edit section *** (Клиенты.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Клиенты.Фамилия Set end)

                // *** End programmer edit section *** (Клиенты.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Клиенты.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Автомобиль CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Автомобиль CustomAttributes)
        public virtual IIS.Snezhko_kursovaya.DetailArrayOfАвтомобиль Автомобиль
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Автомобиль Get start)

                // *** End programmer edit section *** (Клиенты.Автомобиль Get start)
                if ((this.fАвтомобиль == null))
                {
                    this.fАвтомобиль = new IIS.Snezhko_kursovaya.DetailArrayOfАвтомобиль(this);
                }
                IIS.Snezhko_kursovaya.DetailArrayOfАвтомобиль result = this.fАвтомобиль;
                // *** Start programmer edit section *** (Клиенты.Автомобиль Get end)

                // *** End programmer edit section *** (Клиенты.Автомобиль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Автомобиль Set start)

                // *** End programmer edit section *** (Клиенты.Автомобиль Set start)
                this.fАвтомобиль = value;
                // *** Start programmer edit section *** (Клиенты.Автомобиль Set end)

                // *** End programmer edit section *** (Клиенты.Автомобиль Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыE", typeof(IIS.Snezhko_kursovaya.Клиенты));
                }
            }
            
            /// <summary>
            /// "КлиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыL", typeof(IIS.Snezhko_kursovaya.Клиенты));
                }
            }
        }
    }
}
