//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав заказа.
    /// </summary>
    // *** Start programmer edit section *** (СоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (СоставЗаказа CustomAttributes)
    [AutoAltered()]
    [Caption("Состав заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставЗаказаE", new string[] {
            "Услуга as \'Услуга\'",
            "Услуга.Наименование as \'Наименование\'",
            "Услуга.Цена as \'Цена\'"}, Hidden=new string[] {
            "Услуга.Наименование"})]
    [MasterViewDefineAttribute("СоставЗаказаE", "Услуга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class СоставЗаказа : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Snezhko_kursovaya.Услуга fУслуга;
        
        private IIS.Snezhko_kursovaya.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (СоставЗаказа CustomMembers)

        // *** End programmer edit section *** (СоставЗаказа CustomMembers)

        
        /// <summary>
        /// Состав заказа.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Услуга CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Услуга CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуга"})]
        [NotNull()]
        public virtual IIS.Snezhko_kursovaya.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Услуга Get start)

                // *** End programmer edit section *** (СоставЗаказа.Услуга Get start)
                IIS.Snezhko_kursovaya.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (СоставЗаказа.Услуга Get end)

                // *** End programmer edit section *** (СоставЗаказа.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Услуга Set start)

                // *** End programmer edit section *** (СоставЗаказа.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (СоставЗаказа.Услуга Set end)

                // *** End programmer edit section *** (СоставЗаказа.Услуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Snezhko_kursovaya.Заказ.
        /// </summary>
        // *** Start programmer edit section *** (СоставЗаказа.Заказ CustomAttributes)

        // *** End programmer edit section *** (СоставЗаказа.Заказ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказ"})]
        public virtual IIS.Snezhko_kursovaya.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Get start)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Get start)
                IIS.Snezhko_kursovaya.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Get end)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Set start)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (СоставЗаказа.Заказ Set end)

                // *** End programmer edit section *** (СоставЗаказа.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставЗаказаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставЗаказаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставЗаказаE", typeof(IIS.Snezhko_kursovaya.СоставЗаказа));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставЗаказа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставЗаказа CustomAttributes)
    public class DetailArrayOfСоставЗаказа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Snezhko_kursovaya.DetailArrayOfСоставЗаказа members)

        // *** End programmer edit section *** (IIS.Snezhko_kursovaya.DetailArrayOfСоставЗаказа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставЗаказа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставЗаказа.
        /// </summary>
        public DetailArrayOfСоставЗаказа(IIS.Snezhko_kursovaya.Заказ fЗаказ) : 
                base(typeof(СоставЗаказа), ((ICSSoft.STORMNET.DataObject)(fЗаказ)))
        {
        }
        
        public IIS.Snezhko_kursovaya.СоставЗаказа this[int index]
        {
            get
            {
                return ((IIS.Snezhko_kursovaya.СоставЗаказа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Snezhko_kursovaya.СоставЗаказа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
