//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Snezhko_kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип автомобиля.
    /// </summary>
    // *** Start programmer edit section *** (ТипАвтомобиля CustomAttributes)

    // *** End programmer edit section *** (ТипАвтомобиля CustomAttributes)
    public enum ТипАвтомобиля
    {
        
        // *** Start programmer edit section *** (ТипАвтомобиля.1 CustomAttributes)

        // *** End programmer edit section *** (ТипАвтомобиля.1 CustomAttributes)
        [Caption("Легковой")]
        1,
        
        // *** Start programmer edit section *** (ТипАвтомобиля.2 CustomAttributes)

        // *** End programmer edit section *** (ТипАвтомобиля.2 CustomAttributes)
        [Caption("Грузовой")]
        2,
    }
}
